# Generated by Django 4.0.4 on 2022-06-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelpredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsModelPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_type', models.TextField(blank=True, max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('positive_count', models.TextField(max_length=5)),
                ('negetive_count', models.TextField(max_length=5)),
                ('neutral_count', models.TextField(max_length=5)),
                ('total_result', models.TextField(max_length=5)),
                ('query_String', models.TextField(max_length=50)),
                ('source', models.TextField(max_length=100)),
            ],
        ),
    ]
