# Generated by Django 4.0.4 on 2022-06-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newsmodelpredictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredictions',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
