# Generated by Django 4.0.4 on 2022-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_modelpredictions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpredictions',
            name='query_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelpredictions',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
