# Generated by Django 4.0.4 on 2022-06-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_modelpredictions_query_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpredictions',
            name='query_time',
            field=models.DateTimeField(),
        ),
    ]
